### ISSUE TITLE
copy to clipboard

### ISSUE THREAD

**Issue by itsjustjordanhere** [itsjustjordanhere/PWGEN#3]
need to fix copy to clipboard issue

**Comment by tahakocabuga** [comment]
Opened a pull request for this one

**Comment by itsjustjordanhere** [comment]
Greetings, [tahakocabuga](https://github.com/tahakocabuga). 

I'm glad to meet you; I only just realised you were there. The problem was that I removed the variable name while eliminating a portion of the code, which caused a problem with clipboard.

Nonetheless, have a wonderful day.
